apiVersion: v2
name: task-manager ##helm paketitin chart adıdır
description: Flask MongoDB Task Manager - Helm Chart
type: application
version: 0.1.0        # Chart versiyonu
appVersion: "1.0.0"   # Uygulama versiyonu
