apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.name }}-secret
  labels:
    app: {{ .Values.mongodb.name }}
type: Opaque
data:
  mongo-root-username: {{ .Values.mongodb.auth.rootUsername | b64enc | quote }}
  mongo-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.name }}-pvc
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
        - name: {{ .Values.mongodb.name }}
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.name }}-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.name }}-secret
                  key: mongo-root-password
          resources:
            requests:
              cpu: {{ .Values.mongodb.resources.requests.cpu }}
              memory: {{ .Values.mongodb.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mongodb.resources.limits.cpu }}
              memory: {{ .Values.mongodb.resources.limits.memory }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.name }}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}-service
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  type: {{ .Values.mongodb.service.type }}
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
      protocol: TCP
